version: '3.9'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=musicfy

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dynamic


  backend:
    build: ./backend/musicfy/.
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - dynamic

  frontend:
    build: ./frontend/admin/.
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - db
    networks:
      - dynamic


networks:
  dynamic:
    driver: bridge

volumes:
  db:
    driver: local
